# Generated by Django 4.0.3 on 2022-03-07 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vwallet_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='main_user',
        ),
        migrations.AddField(
            model_name='pocket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pockets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
