# Generated by Django 4.0.3 on 2022-03-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vwallet_main', '0002_remove_pocket_main_user_pocket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='user',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='username',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pocket',
            name='main_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pockets', to='vwallet_main.mainuser'),
        ),
    ]
